version: '3.8'
services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      - POSTGRES_DSN=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
    command: ["./app"]
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
